import { Platform } from 'react-native';
import { responsiveHeight, responsiveWidth, responsiveFontSize } from 'react-native-responsive-dimensions';
const styles = {
    container: {
        flex: 8,
        backgroundColor:'transparent',
    },
     wipay:{
      fontSize:responsiveFontSize(4),
      fontWeight:'600',
      color:'white'
    },
    headerImage:{
       height:responsiveWidth(7),
       width:responsiveWidth(7),
    },
    welcome:{
      fontSize:responsiveFontSize(4),
      fontWeight:'400',
      color:'white'
    },
    headerTitle:{
      color:'rgb(0,163,240)',
      fontSize:responsiveFontSize(4),
      alignSelf:'center',
      fontWeight:'300'
    },
    login:{
      color:'white',
      fontSize:16,
      fontWeight:'400',
      alignSelf:'center'
    },
    oneText:{
      fontSize:responsiveFontSize(2),
      fontWeight:'400',
      color:'white',
      alignSelf:'center'
    },
    layout1:{
      alignItems:'center',
      justifyContent:'center',
      flex:1,
      borderColor:'white',
      borderBottomWidth:1,
      borderRightWidth:1
    },
    layout2:{
      flexDirection:'column',
      justifyContent:'center',
      flex:1,
      borderColor:'white',
      borderBottomWidth:1,
      borderRightWidth:1
    },
    layout3:{
      flexDirection:'column',
      justifyContent:'center',
      flex:1,
      borderColor:'white',
      borderBottomWidth:1,
      borderRightWidth:1
    },
    layout4:{
      flexDirection:'column',
      justifyContent:'center',
      flex:1,
      borderColor:'white',
      borderBottomWidth:1,
      borderRightWidth:1
    },
    eachImage:{
      height:responsiveHeight(6),
      alignSelf:'center',
      width:responsiveHeight(6),
    },
    eachText:{
      alignSelf:'center',
      color:'white',
      marginTop:responsiveHeight(1),
      fontSize:responsiveFontSize(2),
    },
    username:{
      width:'80%',
      alignSelf:'center',
      borderBottomWidth:2,
      borderColor:'white',
      fontSize:22,
      paddingBottom:8,
      color:'white'
    },
    loginButton:{
      width:'48%',
      height:35,
      alignSelf:'center',
      borderRadius:15
    },
    forgot:{
      color:'white',
      fontSize:18,
      fontWeight:'400',
      alignSelf:'center'
    },
    line:{
        height:2,
        backgroundColor:'rgb(225,225,225)',
        width:'100%',
        marginBottom:10
    },
    logoutText:{
      fontSize:20,
      fontWeight:'700',
      color:'#14a7fd'
    }
}

export default styles