import { Platform } from 'react-native';

const styles = {
    container: {
        flex: 8,
        backgroundColor:'transparent',
    },
    wipay:{
    	color:'white',
    	fontSize:45,
    	fontWeight:'300',
    	alignSelf:'center',
    },
    login:{
    	color:'white',
    	fontSize:16,
    	fontWeight:'400',
    	alignSelf:'center'
    },
    username:{
    	width:'60%',
    	alignSelf:'center',
    	borderBottomWidth:2,
    	borderColor:'#ddd',
    	fontSize:12,
    	paddingBottom:2,
    	color:'black',
        alignSelf:'center',
        marginTop:5,
        height:40,
        marginTop: 10,
        textAlign:'center',
    },
    rowView:{
        flexDirection:'row',
        width:'60%',
        alignItems:'center',
        justifyContent:'space-between',
        alignSelf:'center',
        marginTop:5,
    },
    loginButton:{
    	width:'40%',
    	height:40,
    	alignSelf:'center',
    	borderRadius:15,
        backgroundColor:'transparent',
        borderColor:'rgb(0,138,220)',
        borderWidth:1
    },
    forgot:{
    	color:'grey',
    	fontSize:12,
    	fontWeight:'500',
    	alignSelf:'flex-start'
    },
    amountsell:{
        color:'grey',
        fontSize:18,
        fontWeight:'800',
        alignSelf:'flex-start',
        alignSelf:'center',
        marginTop:10,
        marginBottom:5,
    },
    wicon:{
        color:'grey',
        fontSize:14,
        fontWeight:'800',
        alignSelf:'flex-start',
        alignSelf:'center',
        marginTop:10
    },
    line:{
        height:2,
        backgroundColor:'rgb(225,225,225)',
        width:'100%',
        marginBottom:10
    },
    labelButtonA:{
        backgroundColor:'rgb(82,151,250)',
        borderRadius:0,
        flex:1,
    },
    labelButton:{
        backgroundColor:'rgb(0,85,227)',
        borderRadius:0,
        flex:1,
    },
    heads:{
        color:'white',
        fontWeight:'600',
    },
    tails:{
       color:'white',
       fontWeight:'200',
    }
}

export default styles